/**
 * The four vocabularies that are not industries: NAICS, SIC, technologies and
 * places.
 *
 * Data only; the pickers and the shape validation live in ./codes. Generated
 * from the source module rather than retyped, for the same reason as the
 * industries: 121 codes with titles, 135 more, 168 product names and 204 places
 * do not survive being typed out by hand.
 *
 * NAICS and SIC carry their official titles, which use the government's words
 * rather than the ones people type. That gap is what CODE_ALIASES bridges.
 */

/** [code, official title]. Apollo takes 2 to 5 digits and prefix-matches. */
export const NAICS: readonly (readonly [string, string])[] = [
  ["11", "Agriculture, forestry, fishing and hunting"],
  ["111", "Crop production"],
  ["112", "Animal production and aquaculture"],
  ["113", "Forestry and logging"],
  ["115", "Support activities for agriculture and forestry"],
  ["21", "Mining, quarrying, and oil and gas extraction"],
  ["211", "Oil and gas extraction"],
  ["212", "Mining, except oil and gas"],
  ["213", "Support activities for mining"],
  ["22", "Utilities"],
  ["221", "Utilities"],
  ["23", "Construction"],
  ["236", "Construction of buildings"],
  ["237", "Heavy and civil engineering construction"],
  ["238", "Specialty trade contractors"],
  ["31", "Manufacturing (food, textiles, apparel)"],
  ["311", "Food manufacturing"],
  ["312", "Beverage and tobacco product manufacturing"],
  ["313", "Textile mills"],
  ["315", "Apparel manufacturing"],
  ["32", "Manufacturing (wood, paper, chemicals, plastics)"],
  ["321", "Wood product manufacturing"],
  ["322", "Paper manufacturing"],
  ["323", "Printing and related support activities"],
  ["324", "Petroleum and coal products manufacturing"],
  ["325", "Chemical manufacturing"],
  ["3254", "Pharmaceutical and medicine manufacturing"],
  ["326", "Plastics and rubber products manufacturing"],
  ["327", "Nonmetallic mineral product manufacturing"],
  ["33", "Manufacturing (metals, machinery, electronics, transport)"],
  ["331", "Primary metal manufacturing"],
  ["332", "Fabricated metal product manufacturing"],
  ["333", "Machinery manufacturing"],
  ["334", "Computer and electronic product manufacturing"],
  ["3341", "Computer and peripheral equipment manufacturing"],
  ["3342", "Communications equipment manufacturing"],
  ["3344", "Semiconductor and other electronic component manufacturing"],
  ["3345", "Navigational, measuring and control instruments manufacturing"],
  ["335", "Electrical equipment, appliance and component manufacturing"],
  ["336", "Transportation equipment manufacturing"],
  ["3361", "Motor vehicle manufacturing"],
  ["3364", "Aerospace product and parts manufacturing"],
  ["337", "Furniture and related product manufacturing"],
  ["339", "Miscellaneous manufacturing"],
  ["3391", "Medical equipment and supplies manufacturing"],
  ["42", "Wholesale trade"],
  ["44", "Retail trade"],
  ["45", "Retail trade"],
  ["48", "Transportation"],
  ["481", "Air transportation"],
  ["482", "Rail transportation"],
  ["483", "Water transportation"],
  ["484", "Truck transportation"],
  ["485", "Transit and ground passenger transportation"],
  ["486", "Pipeline transportation"],
  ["488", "Support activities for transportation"],
  ["49", "Warehousing, couriers and postal"],
  ["492", "Couriers and messengers"],
  ["493", "Warehousing and storage"],
  ["51", "Information"],
  ["512", "Motion picture and sound recording industries"],
  ["513", "Publishing industries"],
  ["5132", "Software publishers"],
  ["516", "Broadcasting and content providers"],
  ["517", "Telecommunications"],
  ["518", "Computing infrastructure, data processing and hosting"],
  ["519", "Web search portals, libraries and other information services"],
  ["52", "Finance and insurance"],
  ["521", "Monetary authorities, central bank"],
  ["522", "Credit intermediation and related activities"],
  ["5221", "Depository credit intermediation (banks)"],
  ["523", "Securities, commodity contracts and other financial investments"],
  ["524", "Insurance carriers and related activities"],
  ["5241", "Insurance carriers"],
  ["5242", "Insurance agencies, brokerages and related activities"],
  ["525", "Funds, trusts and other financial vehicles"],
  ["53", "Real estate and rental and leasing"],
  ["531", "Real estate"],
  ["532", "Rental and leasing services"],
  ["533", "Lessors of nonfinancial intangible assets"],
  ["54", "Professional, scientific and technical services"],
  ["5411", "Legal services"],
  ["5412", "Accounting, tax preparation, bookkeeping and payroll services"],
  ["5413", "Architectural, engineering and related services"],
  ["5414", "Specialized design services"],
  ["5415", "Computer systems design and related services"],
  ["5416", "Management, scientific and technical consulting services"],
  ["5417", "Scientific research and development services"],
  ["5418", "Advertising, public relations and related services"],
  ["5419", "Other professional, scientific and technical services"],
  ["55", "Management of companies and enterprises"],
  ["551", "Management of companies and enterprises"],
  ["56", "Administrative, support and waste management services"],
  ["561", "Administrative and support services"],
  ["5613", "Employment services"],
  ["5615", "Travel arrangement and reservation services"],
  ["5616", "Investigation and security services"],
  ["562", "Waste management and remediation services"],
  ["61", "Educational services"],
  ["611", "Educational services"],
  ["6113", "Colleges, universities and professional schools"],
  ["62", "Health care and social assistance"],
  ["621", "Ambulatory health care services"],
  ["6211", "Offices of physicians"],
  ["6212", "Offices of dentists"],
  ["6215", "Medical and diagnostic laboratories"],
  ["622", "Hospitals"],
  ["623", "Nursing and residential care facilities"],
  ["624", "Social assistance"],
  ["71", "Arts, entertainment and recreation"],
  ["711", "Performing arts, spectator sports and related industries"],
  ["712", "Museums, historical sites and similar institutions"],
  ["713", "Amusement, gambling and recreation industries"],
  ["72", "Accommodation and food services"],
  ["721", "Accommodation"],
  ["722", "Food services and drinking places"],
  ["81", "Other services (except public administration)"],
  ["811", "Repair and maintenance"],
  ["812", "Personal and laundry services"],
  ["813", "Religious, grantmaking, civic and professional organizations"],
  ["92", "Public administration"],
];

/** [code, official title]. Apollo takes exactly 4 digits. */
export const SIC: readonly (readonly [string, string])[] = [
  ["0111", "Wheat farming"],
  ["0211", "Beef cattle feedlots"],
  ["1311", "Crude petroleum and natural gas"],
  ["1531", "Operative builders"],
  ["1541", "General contractors, industrial buildings"],
  ["1731", "Electrical work"],
  ["2011", "Meat packing plants"],
  ["2086", "Bottled and canned soft drinks"],
  ["2111", "Cigarettes"],
  ["2311", "Men's and boys' suits and coats"],
  ["2421", "Sawmills and planing mills"],
  ["2621", "Paper mills"],
  ["2711", "Newspapers: publishing"],
  ["2721", "Periodicals: publishing"],
  ["2731", "Book publishing"],
  ["2812", "Alkalies and chlorine"],
  ["2821", "Plastics materials and resins"],
  ["2834", "Pharmaceutical preparations"],
  ["2836", "Biological products"],
  ["2844", "Perfumes, cosmetics and toilet preparations"],
  ["2911", "Petroleum refining"],
  ["3011", "Tires and inner tubes"],
  ["3089", "Plastics products"],
  ["3241", "Cement, hydraulic"],
  ["3312", "Steel works and blast furnaces"],
  ["3441", "Fabricated structural metal"],
  ["3511", "Turbines and turbine generator sets"],
  ["3559", "Special industry machinery"],
  ["3571", "Electronic computers"],
  ["3572", "Computer storage devices"],
  ["3576", "Computer communications equipment"],
  ["3577", "Computer peripheral equipment"],
  ["3661", "Telephone and telegraph apparatus"],
  ["3663", "Radio and TV broadcasting and communications equipment"],
  ["3674", "Semiconductors and related devices"],
  ["3711", "Motor vehicles and passenger car bodies"],
  ["3721", "Aircraft"],
  ["3812", "Search, detection, navigation and guidance systems"],
  ["3821", "Laboratory apparatus and furniture"],
  ["3841", "Surgical and medical instruments"],
  ["3843", "Dental equipment and supplies"],
  ["3845", "Electromedical apparatus"],
  ["3861", "Photographic equipment and supplies"],
  ["4011", "Railroads, line-haul operating"],
  ["4213", "Trucking, except local"],
  ["4512", "Air transportation, scheduled"],
  ["4513", "Air courier services"],
  ["4731", "Arrangement of transportation of freight and cargo"],
  ["4813", "Telephone communications"],
  ["4832", "Radio broadcasting stations"],
  ["4833", "Television broadcasting stations"],
  ["4841", "Cable and other pay television services"],
  ["4899", "Communications services"],
  ["4911", "Electric services"],
  ["4924", "Natural gas distribution"],
  ["4941", "Water supply"],
  ["5045", "Computers, peripherals and software (wholesale)"],
  ["5065", "Electronic parts and equipment (wholesale)"],
  ["5122", "Drugs and druggists' sundries (wholesale)"],
  ["5411", "Grocery stores"],
  ["5511", "Motor vehicle dealers, new and used"],
  ["5651", "Family clothing stores"],
  ["5812", "Eating places"],
  ["5912", "Drug stores and proprietary stores"],
  ["5944", "Jewelry stores"],
  ["5961", "Catalog and mail-order houses"],
  ["6021", "National commercial banks"],
  ["6022", "State commercial banks"],
  ["6035", "Savings institutions, federally chartered"],
  ["6141", "Personal credit institutions"],
  ["6153", "Short-term business credit institutions"],
  ["6199", "Finance services"],
  ["6211", "Security brokers and dealers"],
  ["6282", "Investment advice"],
  ["6311", "Life insurance"],
  ["6321", "Accident and health insurance"],
  ["6331", "Fire, marine and casualty insurance"],
  ["6411", "Insurance agents, brokers and service"],
  ["6512", "Operators of nonresidential buildings"],
  ["6531", "Real estate agents and managers"],
  ["6552", "Land subdividers and developers"],
  ["6798", "Real estate investment trusts"],
  ["7011", "Hotels and motels"],
  ["7311", "Advertising agencies"],
  ["7319", "Advertising services"],
  ["7331", "Direct mail advertising services"],
  ["7349", "Building cleaning and maintenance services"],
  ["7361", "Employment agencies"],
  ["7363", "Help supply services"],
  ["7371", "Custom computer programming services"],
  ["7372", "Prepackaged software"],
  ["7373", "Computer integrated systems design"],
  ["7374", "Data processing and preparation"],
  ["7375", "Information retrieval services"],
  ["7376", "Computer facilities management services"],
  ["7377", "Computer rental and leasing"],
  ["7378", "Computer maintenance and repair"],
  ["7379", "Computer related services"],
  ["7381", "Detective, guard and armored car services"],
  ["7389", "Business services"],
  ["7812", "Motion picture and video production"],
  ["7832", "Motion picture theaters"],
  ["7929", "Entertainers and entertainment groups"],
  ["7991", "Physical fitness facilities"],
  ["7997", "Membership sports and recreation clubs"],
  ["8011", "Offices and clinics of doctors of medicine"],
  ["8021", "Offices and clinics of dentists"],
  ["8051", "Skilled nursing care facilities"],
  ["8062", "General medical and surgical hospitals"],
  ["8071", "Medical laboratories"],
  ["8082", "Home health care services"],
  ["8093", "Specialty outpatient facilities"],
  ["8111", "Legal services"],
  ["8211", "Elementary and secondary schools"],
  ["8221", "Colleges, universities and professional schools"],
  ["8249", "Vocational schools"],
  ["8299", "Schools and educational services"],
  ["8322", "Individual and family social services"],
  ["8351", "Child day care services"],
  ["8399", "Social services"],
  ["8611", "Business associations"],
  ["8621", "Professional membership organizations"],
  ["8641", "Civic, social and fraternal associations"],
  ["8661", "Religious organizations"],
  ["8711", "Engineering services"],
  ["8712", "Architectural services"],
  ["8721", "Accounting, auditing and bookkeeping services"],
  ["8731", "Commercial physical and biological research"],
  ["8732", "Commercial economic and sociological research"],
  ["8741", "Management services"],
  ["8742", "Management consulting services"],
  ["8744", "Facilities support management services"],
  ["9199", "General government"],
  ["9411", "Administration of educational programs"],
  ["9431", "Administration of public health programs"],
];

/**
 * Display names, which is how Apollo returns them. It takes uids on the way out
 * ("Google Analytics" becomes "google_analytics"), so the picker offers the
 * ordinary product name and the conversion happens in the client.
 */
export const TECHNOLOGIES: readonly string[] = [
  "Google Analytics", "Google Tag Manager", "Adobe Analytics", "Mixpanel", "Amplitude", "Heap",
  "Segment", "Hotjar", "FullStory", "Looker", "Tableau", "Power BI", "Snowflake", "Databricks",
  "Google BigQuery", "Salesforce", "HubSpot", "Microsoft Dynamics", "Zoho CRM", "Pipedrive",
  "Outreach", "Salesloft", "Gong", "Clari", "ZoomInfo", "Apollo", "LinkedIn Sales Navigator",
  "Drift", "Intercom", "Zendesk", "Freshdesk", "Marketo", "Pardot", "Eloqua", "Mailchimp",
  "Klaviyo", "Braze", "Iterable", "Customer.io", "SendGrid", "Mandrill", "Constant Contact",
  "ActiveCampaign", "Marketo Engage", "Google Ads", "Facebook Pixel", "LinkedIn Ads",
  "Microsoft Advertising", "The Trade Desk", "DoubleClick", "Criteo", "AdRoll", "Taboola",
  "Outbrain", "WordPress.org", "WordPress.com", "Drupal", "Joomla", "Contentful", "Sitecore",
  "Adobe Experience Manager", "Webflow", "Squarespace", "Wix", "Shopify", "Shopify Plus",
  "Magento", "WooCommerce", "BigCommerce", "Salesforce Commerce Cloud", "Stripe", "PayPal",
  "Braintree", "Adyen", "Klarna", "Recurly", "Chargebee", "Zuora", "Amazon AWS",
  "Microsoft Azure", "Google Cloud", "Heroku", "DigitalOcean", "Cloudflare", "Akamai", "Fastly",
  "Nginx", "Apache", "Kubernetes", "Docker", "Terraform", "Amazon S3", "Amazon CloudFront",
  "GitHub", "GitLab", "Bitbucket", "Jira", "Jenkins", "CircleCI", "Datadog", "New Relic",
  "Splunk", "Sentry", "PagerDuty", "Grafana", "Microsoft Office 365", "Google Workspace",
  "Slack", "Microsoft Teams", "Zoom", "Asana", "Monday.com", "Notion", "Trello", "Confluence",
  "Smartsheet", "Airtable", "Miro", "Figma", "Dropbox", "Box", "DocuSign", "Adobe Sign",
  "NetSuite", "SAP", "Oracle", "Workday", "QuickBooks", "Xero", "Sage", "ADP", "Gusto",
  "BambooHR", "Greenhouse", "Lever", "Workable", "Expensify", "Coupa", "Bill.com", "Avalara",
  "Okta", "Auth0", "OneLogin", "Duo Security", "CrowdStrike", "Palo Alto Networks", "Fortinet",
  "Proofpoint", "Mimecast", "KnowBe4", "LastPass", "1Password", "MySQL", "PostgreSQL",
  "MongoDB", "Redis", "Elasticsearch", "Microsoft SQL Server", "Oracle Database", "React",
  "Angular", "Vue.js", "Node.js", "Python", "Ruby on Rails", "Java", "PHP", ".NET",
];

/** Countries, then US states, then metros: the three levels the picker offers. */
export const LOCATIONS: readonly string[] = [
  "Argentina", "Australia", "Austria", "Bangladesh", "Belgium", "Brazil", "Bulgaria", "Canada",
  "Chile", "China", "Colombia", "Costa Rica", "Croatia", "Czech Republic", "Denmark", "Ecuador",
  "Egypt", "Estonia", "Finland", "France", "Germany", "Ghana", "Greece", "Hong Kong", "Hungary",
  "Iceland", "India", "Indonesia", "Ireland", "Israel", "Italy", "Japan", "Jordan", "Kenya",
  "Kuwait", "Latvia", "Lithuania", "Luxembourg", "Malaysia", "Mexico", "Morocco", "Netherlands",
  "New Zealand", "Nigeria", "Norway", "Pakistan", "Panama", "Peru", "Philippines", "Poland",
  "Portugal", "Qatar", "Romania", "Saudi Arabia", "Serbia", "Singapore", "Slovakia", "Slovenia",
  "South Africa", "South Korea", "Spain", "Sri Lanka", "Sweden", "Switzerland", "Taiwan",
  "Thailand", "Turkey", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
  "Uruguay", "Vietnam", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
  "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho",
  "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska",
  "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina",
  "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island",
  "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
  "Washington", "West Virginia", "Wisconsin", "Wyoming", "San Francisco, California",
  "San Jose, California", "Los Angeles, California", "San Diego, California",
  "Sacramento, California", "Seattle, Washington", "Portland, Oregon", "Denver, Colorado",
  "Austin, Texas", "Dallas, Texas", "Houston, Texas", "San Antonio, Texas", "Phoenix, Arizona",
  "Salt Lake City, Utah", "Las Vegas, Nevada", "Chicago, Illinois", "Minneapolis, Minnesota",
  "Detroit, Michigan", "Columbus, Ohio", "Cleveland, Ohio", "Indianapolis, Indiana",
  "Kansas City, Missouri", "St. Louis, Missouri", "Nashville, Tennessee", "Atlanta, Georgia",
  "Charlotte, North Carolina", "Raleigh, North Carolina", "Miami, Florida", "Orlando, Florida",
  "Tampa, Florida", "Jacksonville, Florida", "New York, New York", "Brooklyn, New York",
  "Boston, Massachusetts", "Philadelphia, Pennsylvania", "Pittsburgh, Pennsylvania",
  "Baltimore, Maryland", "Washington, District of Columbia", "Richmond, Virginia",
  "Toronto, Canada", "Vancouver, Canada", "Montreal, Canada", "London, United Kingdom",
  "Manchester, United Kingdom", "Dublin, Ireland", "Paris, France", "Berlin, Germany",
  "Munich, Germany", "Amsterdam, Netherlands", "Madrid, Spain", "Barcelona, Spain",
  "Milan, Italy", "Zurich, Switzerland", "Stockholm, Sweden", "Copenhagen, Denmark",
  "Warsaw, Poland", "Lisbon, Portugal", "Tel Aviv, Israel", "Dubai, United Arab Emirates",
  "Bengaluru, India", "Mumbai, India", "Delhi, India", "Hyderabad, India", "Pune, India",
  "Chennai, India", "Singapore", "Tokyo, Japan", "Seoul, South Korea", "Shanghai, China",
  "Beijing, China", "Sydney, Australia", "Melbourne, Australia", "Auckland, New Zealand",
  "Sao Paulo, Brazil", "Mexico City, Mexico", "Buenos Aires, Argentina",
  "Cape Town, South Africa", "Johannesburg, South Africa", "Nairobi, Kenya", "Lagos, Nigeria",
];

/**
 * Ordinary words promoted onto codes that already exist above.
 *
 * Nothing in NAICS is titled "software": the code is 5132, filed under
 * "publishing industries", and 5415 is "computer systems design". So a search
 * for the ordinary word found nothing at all. These only REORDER, never invent:
 * an alias promotes codes from the seed list and every other match still appears
 * underneath.
 */
export const CODE_ALIASES: Readonly<
  Record<string, Readonly<Record<string, readonly string[]>>>
> = {
  "naics": {
    "software": ["5132", "5415", "518"],
    "saas": ["5132", "518"],
    "technology": ["5415", "5132", "518", "334"],
    "tech": ["5415", "5132", "518", "334"],
    "it services": ["5415", "518"],
    "computer": ["5415", "3341", "518"],
    "internet": ["518", "519"],
    "hosting": ["518"],
    "data": ["518"],
    "telecom": ["517"],
    "semiconductor": ["3344"],
    "healthcare": ["62", "621", "622", "3254", "3391"],
    "health": ["62", "621", "622"],
    "hospital": ["622"],
    "pharma": ["3254"],
    "biotech": ["5417", "3254"],
    "medical devices": ["3391"],
    "finance": ["52", "522", "523"],
    "fintech": ["52", "522", "5415"],
    "bank": ["5221", "522"],
    "insurance": ["524", "5241", "5242"],
    "consulting": ["5416", "5419"],
    "marketing": ["5418"],
    "advertising": ["5418"],
    "legal": ["5411"],
    "accounting": ["5412"],
    "engineering": ["5413"],
    "design": ["5414"],
    "research": ["5417"],
    "staffing": ["5613"],
    "recruiting": ["5613"],
    "manufacturing": ["31", "32", "33"],
    "automotive": ["3361"],
    "aerospace": ["3364"],
    "retail": ["44", "45"],
    "ecommerce": ["44", "45"],
    "logistics": ["48", "49", "493", "488"],
    "education": ["61", "611", "6113"],
    "real estate": ["531"],
    "construction": ["23", "236", "237", "238"],
    "energy": ["21", "211", "22", "221"],
    "utilities": ["221"],
    "media": ["512", "513", "516"],
    "hospitality": ["721", "722"],
    "restaurant": ["722"],
    "nonprofit": ["813"],
    "government": ["92"],
    "agriculture": ["11", "111", "112"],
    "security": ["5616"],
  },
  "sic": {
    "software": ["7372", "7371", "7373"],
    "saas": ["7372", "7371"],
    "technology": ["7372", "7371", "7379", "3674"],
    "tech": ["7372", "7371", "7379"],
    "it services": ["7379", "7376", "7373"],
    "computer": ["7372", "7371", "3571", "5045"],
    "internet": ["7375", "7379"],
    "data": ["7374", "7375"],
    "telecom": ["4813", "3661"],
    "semiconductor": ["3674"],
    "healthcare": ["8011", "8062", "2834", "3841"],
    "health": ["8011", "8062", "8082"],
    "hospital": ["8062"],
    "pharma": ["2834", "2836"],
    "biotech": ["2836", "8731"],
    "medical devices": ["3841", "3845"],
    "finance": ["6021", "6022", "6199", "6211"],
    "fintech": ["6199", "7372"],
    "bank": ["6021", "6022", "6035"],
    "insurance": ["6311", "6321", "6331", "6411"],
    "consulting": ["8742", "8741"],
    "marketing": ["7311", "7319"],
    "advertising": ["7311", "7319", "7331"],
    "legal": ["8111"],
    "accounting": ["8721"],
    "engineering": ["8711"],
    "architecture": ["8712"],
    "research": ["8731", "8732"],
    "staffing": ["7361", "7363"],
    "recruiting": ["7361", "7363"],
    "automotive": ["3711", "5511"],
    "aerospace": ["3721", "3812"],
    "retail": ["5411", "5651", "5912", "5944", "5961"],
    "ecommerce": ["5961"],
    "logistics": ["4213", "4731"],
    "education": ["8211", "8221", "8249", "8299"],
    "real estate": ["6531", "6512", "6798"],
    "construction": ["1531", "1541", "1731"],
    "energy": ["1311", "2911", "4911", "4924"],
    "utilities": ["4911", "4924", "4941"],
    "media": ["2711", "2721", "2731", "4832", "4833", "7812"],
    "hospitality": ["7011", "5812"],
    "restaurant": ["5812"],
    "nonprofit": ["8611", "8621", "8641", "8661"],
    "government": ["9199", "9411", "9431"],
    "security": ["7381"],
    "fitness": ["7991"],
  },
};
