import { AGENTS, JOBS, STAGE_LABEL, TDS_SECTIONS } from '@/lib/marketing/content';
import { ROLE_META, USER_ROLES } from '@/lib/domain/workflow';
import { assistSection, reconSection, voucherSection } from '@/lib/nav';

/**
 * What the assistant is allowed to know.
 *
 * Two kinds of thing live here and they are held to different standards.
 *
 * Product documents describe this platform, and they are the only source the
 * assistant may use to answer a question about it. A model asked "how does the
 * approval work" will otherwise produce a confident, plausible, generic answer
 * about approval workflows, and a finance buyer cannot tell that apart from the
 * truth. So the rule enforced in the prompt is: if it is not in a retrieved
 * document, say you do not know. Which puts the burden here, on this file.
 *
 * The roster part of it is not written here at all. It is generated from AGENTS,
 * the same list the public site and the hub render, so the assistant cannot
 * describe a tool as planned after it has gone live, or promise something the
 * marketing page stopped claiming. There is one place a tool's promise is
 * written down and this is not it.
 *
 * Finance documents are the second kind: the method behind the work, written so
 * an answer about a reconciliation or a tax split has something concrete to
 * stand on. They deliberately state almost no statutory figures. The three dates
 * and the four TDS rates that do appear are the ones the site already commits to
 * elsewhere, pulled from the same constants, and each is marked as needing to be
 * checked against the current position. A chartered accountant's own website
 * quoting a rate that changed last April is a worse outcome than the assistant
 * saying it does not carry rates.
 *
 * House style, since every word of this can end up on a customer's screen:
 * short sentences, ordinary words, no em-dashes.
 */

export type DocKind = 'platform' | 'product' | 'finance';

export type Doc = {
  id: string;
  title: string;
  /** The roster slug this belongs to, or null for anything platform-wide. */
  agent: string | null;
  kind: DocKind;
  /**
   * Words that should find this document but do not appear in its body. The
   * vocabulary gap is the whole problem in a corpus this small: somebody types
   * "BRS" and the document says "bank reconciliation statement" throughout.
   */
  keywords?: string[];
  /** Where the reader can go and check, when there is such a page. */
  href?: string;
  body: string;
};

// ─── Generated from the roster ───────────────────────────────────────────────

/**
 * One document per tool, built from the roster entry.
 *
 * `does` is the list the agent's own page prints, and for a live tool that list
 * is a description of what exists rather than a plan. Carrying it verbatim is
 * what keeps the assistant and the website saying the same thing.
 */
function rosterDocs(): Doc[] {
  return AGENTS.map((agent) => ({
    id: `agent-${agent.slug}`,
    title: agent.name,
    agent: agent.slug,
    kind: 'product' as const,
    href: `/agents/${agent.slug}`,
    keywords: [agent.category, agent.stage, STAGE_LABEL[agent.stage]],
    body: [
      `${agent.name} is one of the tools on this platform. Its area is ${agent.category.toLowerCase()}.`,
      `Status: ${STAGE_LABEL[agent.stage]}.`,
      agent.stage === 'live'
        ? `It is built and you can use it now. Inside the app it opens at ${agent.href}.`
        : 'It is not built yet. Nobody can switch it on, and there is no date for it.',
      '',
      agent.summary,
      '',
      agent.pitch,
      '',
      agent.stage === 'live' ? 'What it does today:' : 'What it is meant to do:',
      ...agent.does.map((line) => `- ${line}`),
      '',
      `What goes in: ${agent.inputs}.`,
      `What comes out: ${agent.outputs}.`,
    ].join('\n'),
  }));
}

/** The finance month, as the roster tells it. Answers "when does this happen". */
function calendarDoc(): Doc {
  return {
    id: 'finance-month',
    title: 'The finance month, job by job',
    agent: null,
    kind: 'finance',
    keywords: ['calendar', 'deadline', 'due date', 'monthly', 'routine', 'when'],
    body: [
      'The work a finance team repeats every month, and which tool takes each job.',
      'Only three of these have a fixed statutory date, and those three are for a',
      'monthly filer. Anything that moves with your filing frequency is given as a',
      'band instead. Check your own due dates before relying on any of them.',
      '',
      ...JOBS.flatMap((job) => {
        const agent = AGENTS.find((a) => a.slug === job.agent);
        return [
          `${job.when}: ${job.title}.`,
          `  How it usually goes: ${job.now}`,
          `  The part we take on: ${job.ours}`,
          `  Tool: ${agent ? `${agent.name} (${STAGE_LABEL[agent.stage].toLowerCase()})` : job.agent}`,
          '',
        ];
      }),
    ].join('\n'),
  };
}

/**
 * Where the screens are, generated from the navigation itself.
 *
 * Added after watching the assistant answer "approve this for me" correctly and
 * then send the reader to /dashboard for their approval queue, which is at
 * /approvals. It had nothing to go on: the corpus described what each tool does
 * and never said where anything lives, so the one part of the answer it had to
 * invent was the part the reader would act on.
 *
 * Generated rather than written for the obvious reason. A hand-written list of
 * routes is wrong the first time somebody moves one, and being confidently wrong
 * about where a screen is is worse than not knowing.
 *
 * Built as an owner so every destination appears, with the two that are gated
 * marked as such rather than silently dropped.
 */
function screensDoc(): Doc {
  const sections = [voucherSection({ role: 'owner' }), reconSection(), assistSection()];

  return {
    id: 'platform-screens',
    title: 'Where each screen is',
    agent: null,
    kind: 'platform',
    keywords: ['where', 'find', 'go to', 'screen', 'page', 'menu', 'navigation', 'url', 'link'],
    body: [
      'Signing in takes you to the hub at /hub, which is where you choose a tool.',
      'Each tool then has its own set of screens.',
      '',
      ...sections.flatMap((section) => [
        `${section.name}, which opens at ${section.home}:`,
        ...section.items.map((item) => `- ${item.label}, at ${item.href}. ${item.hint}.`),
        ...(section.primary ? [`- ${section.primary.label}, at ${section.primary.href}.`] : []),
        '',
      ]),
      'Two of those are only there for some people. Approvals is for approvers,',
      'admins and owners. Admin is for admins and owners. A member sees neither.',
      '',
      'Settings is the same screen from every tool. So is the hub.',
    ].join('\n'),
  };
}

/** The role ladder, from the same table the settings screen prints. */
function rolesDoc(): Doc {
  return {
    id: 'platform-roles',
    title: 'Roles and what each one can do',
    agent: null,
    kind: 'platform',
    keywords: ['permission', 'access', 'who can', 'admin', 'owner', 'approver', 'member'],
    href: '/settings',
    body: [
      'One account works across every tool, and one role decides what it can do',
      'everywhere. Being allowed to approve a payment means the same thing in each',
      'tool, and the database is what enforces it rather than each screen.',
      '',
      'The ladder, weakest first. Every role can do what the ones before it can.',
      ...USER_ROLES.map((role) => `- ${ROLE_META[role].label}: ${ROLE_META[role].grants}`),
      '',
      "Only an owner can change somebody else's role. An owner cannot demote another",
      'owner, and cannot demote themselves. Roles are changed on the admin screen.',
      '',
      'Ledger Reconciliation has no role rules of its own. Nothing in it is approved',
      'or paid, so there is nothing an approver can do there that a member cannot.',
    ].join('\n'),
  };
}

/** The four TDS sections the site's own calculator knows about. */
function tdsDoc(): Doc {
  return {
    id: 'finance-tds',
    title: 'TDS, and the sections this site carries',
    agent: null,
    kind: 'finance',
    keywords: ['194C', '194H', '194J', 'withholding', 'deduct at source', 'tax deducted'],
    body: [
      'TDS is tax deducted at source. The person paying withholds a percentage of',
      'the payment and deposits it against the payee, so the payee receives the',
      'balance and gets credit for the amount withheld.',
      '',
      'On a voucher it comes off the net total, before the grand total. Deducting at',
      'the wrong rate is usually found a quarter later, when correcting it costs',
      'interest, so the time to get it right is while the voucher is still a draft.',
      '',
      'This site carries four sections, and only four. They are the ones behind the',
      'calculator on the home page, and they are here so the assistant and that',
      'calculator cannot disagree.',
      ...TDS_SECTIONS.filter((s) => s.code !== 'None').map(
        (s) => `- ${s.code}: ${s.rate}%. ${s.note}.`,
      ),
      '',
      'That is not a complete list of sections, it is not a complete statement of any',
      'of them, and rates change. A higher rate applies where a PAN is missing or',
      'inoperative. Always confirm the current position for your own case before',
      'deducting. The assistant should say so rather than answer as if this table',
      'settled the question.',
      '',
      'TDS Compliance, the tool meant to work the section and rate out for you and',
      'build the quarterly returns, is on the roadmap and is not built.',
    ].join('\n'),
  };
}

// ─── Written by hand ─────────────────────────────────────────────────────────

const WRITTEN: Doc[] = [
  {
    id: 'platform-overview',
    title: 'What The Finance Intelligence is',
    agent: null,
    kind: 'platform',
    keywords: ['product', 'company', 'platform', 'what is this', 'overview', 'tools', 'agents'],
    href: '/agents',
    body: [
      'The Finance Intelligence is a platform of tools for finance work, built by',
      'chartered accountants. Each tool takes one job a finance team already',
      'repeats, does the routine part of it, and keeps a clear record of who did',
      'what and when.',
      '',
      'There are six tools on the roster. Two are built and you can use them today.',
      'Four are written up and not started. Every screen that lists them says which',
      'is which, and the assistant must do the same. Describing a roadmap tool as if',
      'it were available is the single worst thing it can do.',
      '',
      'What the tools share is one sign-in, one list of who can do what, one set of',
      'records, and one history. That is the reason to have them from one place.',
      '',
      'Signing in takes you to the hub, which is the screen for choosing a tool. Each',
      'tool then has its own workspace with its own navigation.',
    ].join('\n'),
  },
  {
    id: 'platform-privacy',
    title: 'Where your data goes',
    agent: null,
    kind: 'platform',
    keywords: ['security', 'privacy', 'gdpr', 'upload', 'server', 'storage', 'confidential'],
    body: [
      'The application and its database both run in Mumbai.',
      '',
      'Ledger Reconciliation is the strictest case, because the files are client bank',
      'statements. Both ledgers are read inside your own browser and are never',
      'uploaded. The engine that matches them runs there too. The only thing that',
      'ever reaches a server is the finished statement, and only when you save it to',
      'your history or ask for a PDF or an Excel file.',
      '',
      'Voucher Desk keeps its records in the database, because a voucher is a record',
      'other people have to approve. Invoice attachments go to file storage, and who',
      'can open one mirrors who can see the voucher it belongs to.',
      '',
      'What you type to this assistant is sent to Anthropic, and answered by Claude. Do',
      'not paste anything into it that you would not send to a third party. It is not',
      'given a connection to your vouchers, your ledgers or your history, so it cannot',
      'read your records even if you ask it to.',
    ].join('\n'),
  },
  {
    id: 'assistant-limits',
    title: 'What this assistant can and cannot do',
    agent: null,
    kind: 'platform',
    keywords: ['you', 'yourself', 'chatbot', 'assistant', 'help', 'can you', 'ai'],
    body: [
      'The assistant answers questions. It explains how the tools work, walks through',
      'the finance and accounting behind them, and does the arithmetic using the',
      'same code the application itself uses.',
      '',
      'It cannot do anything on your behalf. It cannot raise a voucher, approve one,',
      'reject one, mark one paid, run a reconciliation, upload a file, change a role',
      'or delete a record. It has no connection to the database. If you ask it to do',
      'any of those, the right answer is to say so and point at the screen that does',
      'it.',
      '',
      'It cannot see your records. It does not know how many vouchers you have, what',
      'is in your approval queue, or what your last reconciliation said. If you want',
      'it to reason about a figure, paste the figure in.',
      '',
      'It is not a substitute for professional advice, and it is not the filing. On',
      'anything statutory it should give you the method and tell you to confirm the',
      'current position.',
    ].join('\n'),
  },
  {
    id: 'platform-organisation',
    title: 'What an organisation is, and where its name comes from',
    agent: null,
    kind: 'platform',
    keywords: [
      'organisation',
      'organization',
      'org',
      'company',
      'firm',
      'tenant',
      'rename',
      'name',
      'onboarding',
      'sign up',
      'first time',
    ],
    href: '/settings',
    body: [
      'An organisation is the thing everything else belongs to. Vouchers, chapters,',
      'people and roles all sit inside one, and nothing is ever shared across two.',
      '',
      'An account belongs to exactly one. You either create one, which makes you its',
      "owner, or you follow an invite link into somebody else's. There is no way to",
      'belong to two at once, and no way to move yourself from one to another.',
      '',
      'A new organisation does not start empty. Creating one also creates a chapter',
      'called Head Office, so the first voucher can be raised without setting',
      'anything up first.',
      '',
      'The name is typed when the organisation is created, and it can be changed',
      'afterwards. Only the owner can change it, on the settings screen at /settings.',
      'Everybody else sees the name there and cannot edit it. It is worth getting',
      'right, because it is the name anybody following an invite link is asked to',
      'join.',
    ].join('\n'),
  },
  {
    id: 'platform-invites',
    title: 'Inviting somebody, and how the link works',
    agent: null,
    kind: 'platform',
    keywords: [
      'invite',
      'invitation',
      'add a person',
      'add a user',
      'new joiner',
      'teammate',
      'colleague',
      'join',
      'link',
      'token',
      'expired',
      'revoke',
      'no email',
    ],
    href: '/admin',
    body: [
      'People are invited from Admin → People, which is /admin. An admin or an owner',
      'gives an email address and a role, and gets a link back.',
      '',
      'The link is the invite. Whether an email carrying it also goes out depends on',
      'whether the deployment has a mail provider configured, and the screen says',
      'which. Where it does not, no email is sent at all: the admin copies the link',
      'and sends it however they already reach that person. Nobody should be left',
      'waiting for an invitation that was never going to arrive.',
      '',
      'A link lasts fourteen days. An admin can revoke one that has not been accepted',
      'yet, and that is also how to replace an invite: only one live invite per',
      'address is allowed at a time.',
      '',
      'The address on the invite is what binds it. Whoever follows the link has to be',
      'signed in to an account with that same address, so a link that gets forwarded',
      'to somebody else does not let them join as the person who was invited.',
      '',
      'An invite can carry any role except owner. An owner can change it afterwards',
      'on the same screen. Inviting somebody who is already in the organisation is',
      'refused rather than producing a link that could never work.',
    ].join('\n'),
  },
  {
    id: 'voucher-workflow',
    title: 'The voucher approval workflow',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: [
      'approve',
      'reject',
      'send back',
      'submit',
      'sign off',
      'segregation of duties',
      'status',
      'draft',
      'pending',
    ],
    body: [
      'Whether a voucher needs approval at all is a setting each organisation',
      'chooses for itself, on the admin screen. Turned off, a submitted voucher',
      'goes straight to paid. Turned on, it needs one approval before it is paid.',
      '',
      '  draft, submit, awaiting approval (if the organisation requires it), approved, paid',
      '',
      'A voucher can be sent back while it is awaiting approval, and a sent back',
      'voucher goes to the back of the queue rather than staying where it left off.',
      '',
      'The rules are enforced in the database, not in the browser, so they hold',
      'whether the request comes from this website, from a script, or from anywhere',
      'else.',
      '',
      '- The person who raised a voucher can never approve it, even if they are the',
      '  only other approver in the organisation.',
      '- Sending one back requires a reason. Any approval already given is voided, so',
      '  the next run starts clean.',
      '- An approved or paid voucher cannot be edited. A trigger blocks it.',
      '- Every step is written to a history that has no update and no delete rule.',
      '  Not even the owner of the account can rewrite it.',
      '',
      'A voucher can be edited while it is a draft or after it has been sent back,',
      'and at no other time.',
      '',
      'Older vouchers, raised before an organisation could turn approval off, may',
      'still show a "1st" and "2nd" approval on their history. That was the workflow',
      'before it changed to one approval; it still displays correctly on the',
      'vouchers that went through it, but no new voucher can enter it.',
      '',
      'This is the part the old portal did not have. There, approval was a free text',
      'box typed by whoever created the voucher. There was no status, no approver',
      'identity, no timestamps, no rejection path and no history, so a voucher could',
      "be approved by typing a colleague's name.",
    ].join('\n'),
  },
  {
    id: 'voucher-chapters',
    title: 'Chapters, and why every voucher needs one',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: [
      'chapter',
      'branch',
      'unit',
      'location',
      'head office',
      'HO',
      'dropdown',
      'empty',
      'nothing to choose',
      'cannot select',
      'add a chapter',
      'retire',
    ],
    href: '/admin/chapters',
    body: [
      'A chapter is the part of the organisation a voucher belongs to. A branch, a',
      'unit, a regional body. Every voucher has to name one, and it is where the',
      'chapter code in the voucher number comes from.',
      '',
      'So an organisation with no chapters in it cannot raise anything at all. If the',
      'Chapter dropdown on a new voucher has nothing in it, that is the reason, and',
      'adding a chapter is the whole of the fix. Nothing else is wrong.',
      '',
      'Chapters are added and renamed at Admin → Chapters, which is /admin/chapters.',
      'Only an admin or an owner can get to it. A chapter needs a name and a code of',
      'two to six letters or digits. The code is embedded in every voucher number',
      'that chapter ever issues, so it is fixed when the chapter is created and',
      'cannot be changed afterwards. The name can be changed at any time.',
      '',
      'A new organisation already has one. Creating an organisation creates a chapter',
      'called Head Office with the code HO, which is enough to raise the first',
      'voucher, and it can be renamed like any other.',
      '',
      'A chapter is retired rather than deleted, because vouchers already point at it.',
      'Retiring it stops it being offered on new vouchers and leaves it on the old',
      'ones.',
      '',
      'Paid By Chapter on a voucher may only be head office or the chapter the',
      'voucher is for.',
    ].join('\n'),
  },
  {
    id: 'voucher-approval-setting',
    title: 'Whether vouchers need approving, and who decides',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: [
      'requires approval',
      'turn on',
      'turn off',
      'switch off',
      'default',
      'policy',
      'setting',
      'straight to paid',
      'no approver',
      'nobody to approve',
    ],
    href: '/admin',
    body: [
      'Approval is off when an organisation is created. Until somebody turns it on, a',
      'submitted voucher is paid immediately and nobody has to sign anything off.',
      '',
      'It is turned on at Admin → People, which is /admin, and only the owner can do',
      'it. An admin does not see the control.',
      '',
      'Turned on, a submitted voucher waits for one approval before it can be paid,',
      'and the approval can never come from the person who raised it. That is why the',
      'screen warns an organisation with fewer than two people who can approve: some',
      'vouchers would have nobody left to clear them.',
      '',
      'Changing the setting does not reach back. Vouchers already waiting stay where',
      'they are.',
    ].join('\n'),
  },
  {
    id: 'voucher-numbers',
    title: 'How voucher numbers are given out',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: ['number', 'numbering', 'sequence', 'reference', 'FI/', 'duplicate'],
    body: [
      'A voucher number looks like FI/CHAPTER/25-26/0001.',
      '',
      'It is generated by the database when the voucher is submitted, not when it is',
      'created, so drafts that are abandoned do not burn a number. The sequence runs',
      'per chapter, per financial year, and the number is unique. Nobody types one by',
      'hand.',
      '',
      'The financial year in the middle is the Indian one, 1 April to 31 March.',
      '',
      'In the old portal numbers were typed by hand and duplicates were possible.',
    ].join('\n'),
  },
  {
    id: 'voucher-amounts',
    title: 'The amount ladder on a voucher',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: [
      'total',
      'net total',
      'grand total',
      'formula',
      'calculation',
      'advance',
      'discount',
      'tips',
      'basic value',
    ],
    body: [
      'The figures on a voucher are worked out in a fixed order. The letters are the',
      'ones printed on the form.',
      '',
      '  A  Basic Value',
      '  B  Total Tax, which is CGST plus SGST plus IGST',
      '  C  VAT or other charges',
      '  D  Net Total, which is A plus B plus C',
      '  E  TDS',
      '  G  Advance',
      '  H  Tips',
      '  I  Discount',
      '',
      '  Grand Total = D minus E minus G plus H minus I',
      '',
      'Note the two signs people expect the other way round. Tips are added. An',
      'advance is subtracted, because it has already been paid out, so it comes off',
      'what is still owed.',
      '',
      'The database computes the net total and the grand total as generated columns.',
      'They cannot drift from what is on screen, because the screen is not what',
      'calculates them. In the old portal both were worked out in the browser and',
      'stored as whatever it sent.',
    ].join('\n'),
  },
  {
    id: 'voucher-gst',
    title: 'GST on a voucher',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: ['cgst', 'sgst', 'igst', 'intra state', 'inter state', 'gst', 'tax'],
    body: [
      'A voucher is either intra-state or inter-state, and never both.',
      '',
      'Intra-state means the supplier and the place of supply are in the same state.',
      'The tax splits into CGST and SGST, normally half the rate each.',
      '',
      'Inter-state means they are in different states. The whole amount is IGST.',
      '',
      'The form enforces this three times over. The opposite fields are disabled',
      'while you type, the voucher cannot be submitted with both filled, and the',
      'database has a check constraint so it holds regardless of client.',
      '',
      'Total tax is CGST plus SGST plus IGST, which is line B of the amount ladder.',
    ].join('\n'),
  },
  {
    id: 'voucher-fields',
    title: 'What a voucher asks for',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: [
      'field',
      'form',
      'supporting',
      'proforma',
      'reimbursement',
      'contract',
      'advance',
      'full payment',
      'chapter',
      'event',
      'payee',
    ],
    body: [
      'The form carries all thirty-two fields from the voucher the team already used,',
      'so the printed page looks the way it always has. They cover the payee, the',
      'chapter and event it belongs to, the supporting document, the amounts, and the',
      'payment details.',
      '',
      'Type of Supporting decides Type of Payment.',
      '- Invoice: either an advance or a full payment. You choose.',
      '- Proforma Invoice: advance only, and it is preselected.',
      '- Reimbursement: full payment only, and it is preselected.',
      '- Contract: advance only, and it is preselected.',
      '',
      'Paid By Chapter may only be head office or the chapter the voucher is for.',
      '',
      'PAN and GSTIN are checked for format as you type, and the GSTIN check includes',
      'its checksum digit, which catches transposed digits a pattern match would let',
      'through. If both are given, the PAN inside the GSTIN must match the PAN.',
      '',
      'Drafts save themselves as you work, and only you can see your own draft.',
    ].join('\n'),
  },
  {
    id: 'voucher-outputs',
    title: 'Getting a voucher out of the system',
    agent: 'voucher-desk',
    kind: 'product',
    keywords: ['pdf', 'excel', 'export', 'print', 'download', 'attachment', 'invoice', 'audit'],
    body: [
      'A voucher prints as a PDF you can search, because the text in it is real text.',
      'The old portal produced a picture of the screen.',
      '',
      'The register exports to Excel with the same thirty-two columns the team',
      'already works from, with real numbers and real dates rather than strings, and',
      'it respects whatever filters the register is showing.',
      '',
      'An invoice can be attached to a voucher. It uploads straight to storage, is',
      'viewed through a signed link, and who can open it mirrors who can see the',
      'voucher. The approval queue warns when a voucher has no invoice attached.',
      '',
      'Every voucher carries its own history: who did what, when, and with what',
      'reason. It cannot be edited or deleted by anybody.',
    ].join('\n'),
  },
  {
    id: 'recon-how',
    title: 'Running a reconciliation, step by step',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: ['how to', 'steps', 'start', 'upload', 'columns', 'run', 'wizard'],
    href: '/reconcile',
    body: [
      'Four steps.',
      '',
      '1. Give it two ledgers. Usually your own books and the bank statement. Excel,',
      '   CSV or a text PDF. There is a sample pair on the screen if you want to see',
      '   it work before using your own.',
      '2. Confirm the columns. It works out what each column is from its heading, and',
      '   you correct it where the two files use different words for the same thing.',
      '   You can also name each book here, which is what the statement will call it.',
      '3. Choose the settings. Which ledger you are reconciling from, the date you are',
      '   reconciling as at, and how many days of timing difference to allow.',
      '4. Read the statement. It says whether the two tie out, lists what is left, and',
      '   exports.',
      '',
      'Problems with a file are shown as soon as they are known, and stay on screen',
      'through the steps where you can still do something about them.',
      '',
      'Everything here happens in your browser. Nothing is uploaded.',
    ].join('\n'),
  },
  {
    id: 'recon-matching',
    title: 'How the two ledgers are matched',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: ['match', 'matching', 'pass', 'reference', 'narration', 'cheque', 'algorithm'],
    body: [
      'Matching runs in six passes, strongest evidence first. Once an entry is',
      'matched it is out of the running for the passes that follow.',
      '',
      '1. The reference, when both sides carry one. A cheque or UTR number is the best',
      '   evidence there is.',
      '2. The description and the amount together.',
      '3. The description alone.',
      '4. A contra amount, meaning a debit in one book against a credit of the same',
      '   size in the other.',
      '5. The amount alone.',
      '6. Whatever is left, which is one-sided.',
      '',
      'The order is the point. A cheque number counts for more than a round figure',
      'that happens to turn up twice.',
      '',
      'References are compared with punctuation, spacing and leading zeros stripped,',
      'so CHQ #000123 and chq-123 are the same reference.',
      '',
      'Matching is deterministic. The same two files produce the same statement every',
      'time.',
    ].join('\n'),
  },
  {
    id: 'recon-contra',
    title: 'When one ledger is the mirror of the other',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: ['contra', 'mirror', 'opposite', 'bank statement', 'cash book', 'sides'],
    body: [
      'A bank statement is written from the bank side. Money you pay in is a credit',
      'there, because the bank now owes it to you, while the same entry is a debit in',
      'your cash book. So a bank statement and a cash book are mirrors of each other,',
      'and every matched pair sits on opposite sides.',
      '',
      'The tool detects this from the entries the two books share, and not from their',
      'closing balances. That is deliberate. A single large timing difference can flip',
      'a closing balance from one side to the other, so a balance is not evidence of',
      'which convention a file was written in. Matched entries are.',
      '',
      'Once it knows, it treats an opposite-side match as agreement rather than as a',
      'difference, and it says so on the line: matched, contra entry.',
      '',
      'Two files written the same way round, such as two sides of an intercompany',
      'account extracted from the same system, are handled the same way. The detection',
      'simply finds they are not mirrors.',
    ].join('\n'),
  },
  {
    id: 'recon-statement',
    title: 'The statement it produces',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: [
      'statement',
      'brs',
      'add',
      'less',
      'variance',
      'tie out',
      'balance',
      'reconciled',
      'unexplained',
    ],
    body: [
      'The statement is the usual one. It starts from the balance of the ledger you',
      'are reconciling from, adds and subtracts each difference, and arrives at what',
      'the other book should say.',
      '',
      'Underneath, it is computed in a single signed space where a debit is positive:',
      '',
      '  closing = opening + total debits - total credits',
      '',
      'and then projected onto the side the starting ledger is on. That is why',
      'starting from a credit balance needs no separate rule and produces no phantom',
      'difference.',
      '',
      'It reports one of three outcomes.',
      '- Reconciled: the two tie out and every difference is accounted for.',
      '- Partial: the differences are listed but something is still unexplained.',
      '- Not reconciled: the two do not agree and the statement says by how much.',
      '',
      'The variance is the unexplained part, after every listed difference has been',
      'applied. A clean pair ties out to zero with every difference still shown, so',
      'nobody is left with a residual to chase.',
    ].join('\n'),
  },
  {
    id: 'recon-differences',
    title: 'The four kinds of difference, and what to do about each',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: [
      'difference',
      'timing',
      'one sided',
      'unpresented',
      'uncleared',
      'rounding',
      'decimal',
      'exception',
    ],
    body: [
      'Every line left after matching is put in one of four groups, and each arrives',
      'with a note saying why it is there.',
      '',
      'Matched. The two sides agree. Nothing to do.',
      '',
      'Timing. The same entry is in both books but on dates further apart than the',
      'tolerance you set. A cheque written on the 28th and cleared on the 3rd is the',
      'ordinary case. It is real and it will clear itself, so it goes on the statement',
      'as two equal and opposite legs that net to nothing.',
      '',
      'One-sided. The entry is in one book and not the other. Bank charges and',
      'interest you did not know about, or a cheque you have written that has not been',
      'presented. Either you post it or you wait for it.',
      '',
      'Amount difference. The same entry, matched, but for different figures. The tool',
      'names the likely cause: rounding, a decimal point in the wrong place, or one',
      'figure being a multiple of the other. That last one usually means a quantity',
      'was entered twice.',
      '',
      'The tolerance is measured in days either side of the starting ledger entry, and',
      "it is checked against the other side's clearing date where there is one.",
    ].join('\n'),
  },
  {
    id: 'recon-files',
    title: 'What files it can read',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: ['excel', 'csv', 'pdf', 'xlsx', 'tally', 'scan', 'format', 'file', 'import'],
    body: [
      'Excel, CSV, and PDFs whose text is real text.',
      '',
      'The PDF reader rebuilds the table from where the words are on the page, which',
      'is what a bank statement needs: they are printed as columns with no lines',
      'around them, so the columns exist only as positions.',
      '',
      'A scanned PDF, meaning a photograph of a page with no text behind it, is',
      'refused with an explanation. It is not read as an empty ledger and it is not',
      'guessed at.',
      '',
      'Dates are read in several forms, including 01-Apr-2026 and April 1, 2026.',
      'Where a date is written 01/04/2026 it is read day first, which is how a ledger',
      'in India is printed, unless day first is impossible.',
      '',
      'Amounts are read in Indian or western grouping, with or without a currency',
      'symbol. A figure in brackets is negative. A dash is zero. A Dr or Cr marker on',
      'a figure beats the column it is sitting in, because that is how the balancing',
      'column of a printed ledger works.',
      '',
      'A row whose amount is text rather than a number is dropped and reported, rather',
      'than being quietly read as zero.',
    ].join('\n'),
  },
  {
    id: 'recon-outputs',
    title: 'Exports and history',
    agent: 'ledger-reconciliation',
    kind: 'product',
    keywords: ['export', 'pdf', 'excel', 'workbook', 'save', 'history', 'csv', 'working paper'],
    href: '/reconcile/history',
    body: [
      'Three ways out.',
      '',
      'A PDF working paper, laid out for the file.',
      '',
      'An Excel workbook of three sheets: the summary, the statement, and the lines.',
      'The figures in it are real numbers, so you can carry on working in it.',
      '',
      'A CSV of whatever the differences table is currently showing, filters included.',
      '',
      'Every run you save goes to your own history. Nobody else can see it. A saved',
      'reconciliation cannot be edited, by anyone, including you. Running it again',
      'makes a new one rather than changing the old one, which is what makes the',
      'history worth having.',
      '',
      'The PDF prints figures without the rupee sign, and states the currency once in',
      'the header instead. The font used is one every PDF reader already has, and it',
      'has no rupee glyph. Embedding a font that did would have made a small file',
      'large for one character.',
    ].join('\n'),
  },
  {
    id: 'finance-brs',
    title: 'What a bank reconciliation is for',
    agent: null,
    kind: 'finance',
    keywords: ['brs', 'bank reconciliation statement', 'why', 'purpose', 'month end', 'closing'],
    body: [
      'Your cash book and your bank statement are two records of the same account,',
      'kept by two people who learn about each entry at different times. A',
      'reconciliation explains the gap between them.',
      '',
      'They differ for four ordinary reasons.',
      '- Timing. You wrote a cheque, the bank has not seen it yet.',
      '- Entries only the bank knows about. Charges, interest, a direct debit.',
      '- Entries only you know about. A deposit banked after the cut-off.',
      '- Errors, on either side.',
      '',
      'The point of the exercise is not to make the two numbers equal. It is to be',
      'able to say why they are not, line by line, so that anything left over is a',
      'real problem rather than an unexplained one. A difference nobody can explain,',
      'parked in suspense and carried forward, is how a fraud stays hidden.',
      '',
      'It is worth doing every month for the same reason it is worth doing at all.',
      'The longer the gap, the more entries there are to look through and the colder',
      'the trail on any of them.',
    ].join('\n'),
  },
  {
    id: 'finance-double-entry',
    title: 'Debits, credits and which way round they go',
    agent: null,
    kind: 'finance',
    keywords: [
      'debit',
      'credit',
      'dr',
      'cr',
      'double entry',
      'sign',
      'balance type',
      'convention',
    ],
    body: [
      'Every entry is a debit somewhere and a credit somewhere else, of the same',
      'amount. That is the whole of it.',
      '',
      'A debit increases an asset or an expense, and decreases a liability, income or',
      'capital. A credit does the opposite.',
      '',
      'The place this catches people is the bank. Your bank account is an asset to',
      'you, so money coming in is a debit in your books. To the bank it is a',
      'liability, because they owe it back to you, so the same money is a credit on',
      'their statement. Neither is wrong. They are two people describing the same',
      'event from opposite sides.',
      '',
      'This is why a bank statement read straight into a reconciliation tool looks',
      'inverted, and why a deposit column maps to a credit while a withdrawal column',
      'maps to a debit.',
      '',
      'A useful way to hold a ledger in your head is as one signed number where a',
      'debit is positive:',
      '',
      '  closing = opening + total debits - total credits',
      '',
      'A positive result is a debit balance and a negative one is a credit balance.',
      'Everything else is presentation.',
    ].join('\n'),
  },
  {
    id: 'finance-gst',
    title: 'How GST splits, and why place of supply decides it',
    agent: null,
    kind: 'finance',
    keywords: [
      'gst',
      'cgst',
      'sgst',
      'igst',
      'place of supply',
      'input tax credit',
      'gstr',
      '2b',
      'itc',
    ],
    body: [
      'GST is one tax collected in two shapes, and which shape depends on where the',
      'supply happens rather than on who the parties are.',
      '',
      'Supplier and place of supply in the same state: the tax is split into CGST and',
      'SGST, normally half the rate each. The centre takes one half and the state',
      'takes the other.',
      '',
      'Different states: the whole amount is IGST, and it is settled between the',
      'centre and the states afterwards.',
      '',
      'It is never both. A line showing CGST, SGST and IGST together is an error.',
      '',
      'Input tax credit is the tax you paid on your purchases, set against the tax you',
      'owe on your sales. Credit you forget to claim is money left behind. Credit you',
      'claim wrongly brings a notice. Both come out of the same check, which is',
      'matching what your suppliers have reported against what you have recorded.',
      '',
      'GST Reconciliation, the tool meant to do that matching, is on the roadmap and',
      'is not built. Rates and rules change, so confirm the current position for your',
      'own case.',
    ].join('\n'),
  },
  {
    id: 'finance-year',
    title: 'The financial year, and why the app cares',
    agent: null,
    kind: 'finance',
    keywords: ['fy', 'financial year', 'fiscal', 'april', 'march', 'year end', '25-26'],
    body: [
      'The Indian financial year runs from 1 April to 31 March. A date in March 2026',
      'is in the year written 25-26. A date in April 2026 is in 26-27.',
      '',
      'It matters here in two places. Voucher numbers carry the year they were',
      'submitted in, so the same sequence starts again each April. And every screen',
      'in the app shows the current year and how much of it is left, worked out in',
      'Asia/Kolkata rather than in whatever timezone the server is in.',
      '',
      'That timezone detail is not fussiness. The servers run in UTC, and between',
      'half past six in the evening and midnight India time, a naive reading of the',
      'clock is already on the previous day. For an application whose numbers embed',
      'the year, that is an off-by-one that ends up in a filing.',
    ].join('\n'),
  },
  {
    id: 'finance-identifiers',
    title: 'PAN and GSTIN, and how to tell a bad one',
    agent: null,
    kind: 'finance',
    keywords: ['pan', 'gstin', 'gst number', 'valid', 'format', 'checksum', 'verify'],
    body: [
      'A PAN is ten characters: five letters, four digits, one letter.',
      '',
      'A GSTIN is fifteen. The first two digits are the state code. The next ten are',
      'the PAN of the holder. The thirteenth is the entity number for that PAN in that',
      'state, the fourteenth is Z, and the fifteenth is a check character.',
      '',
      'Two things follow from that, and the app checks both. The check character is a',
      'calculation over the other fourteen, so a GSTIN with a transposed digit fails',
      'arithmetic even though it looks perfectly well formed. And if you have been',
      'given a PAN and a GSTIN for the same party, characters three to twelve of the',
      'GSTIN must be that PAN. If they are not, one of the two is wrong.',
      '',
      'Passing these checks means the number is well formed. It does not mean it is',
      'registered, active, or the right party. For that you have to look it up.',
    ].join('\n'),
  },
];

/** The whole corpus, generated part first. */
export const DOCS: Doc[] = [
  ...rosterDocs(),
  screensDoc(),
  rolesDoc(),
  calendarDoc(),
  tdsDoc(),
  ...WRITTEN,
];

export function docById(id: string): Doc | undefined {
  return DOCS.find((d) => d.id === id);
}
